services:
   rmf_web_dashboard:
     container_name: rmf_web_dashboard_c
     image: ghcr.io/cardboardcode/rmf_dashboard:jazzy
     environment:
      RMF_SERVER_URL: http://localhost:8000
      TRAJECTORY_SERVER_URL: http://localhost:8006
      PORT: 3000
     network_mode: "host"
     restart: unless-stopped
   rmf_web_api_server:
     container_name: rmf_web_api_server_c
     image: ghcr.io/cardboardcode/rmf_api_server:jazzy
     environment:
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      RCUTILS_COLORIZED_OUTPUT: 1
     network_mode: "host"
     restart: unless-stopped
   rmf_core:
     container_name: rmf_core_c
     image: ghcr.io/cardboardcode/rmf_core:jazzy
     volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
     environment:
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      DISPLAY: $DISPLAY
      RCUTILS_COLORIZED_OUTPUT: 1
     devices:
      - "/dev/dri:/dev/dri"
     network_mode: "host"
     healthcheck: 
      test: "bash /rmf_core_ws/check_health.bash"
      interval: 30s
      timeout: 1m
      retries: 2
     restart: unless-stopped
   fleet_adapter_invisibot:
     container_name: fleet_adapter_invisibot_c
     image: ghcr.io/cardboardcode/fleet_adapter_invisibot:jazzy
     environment:
       RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
       RCUTILS_COLORIZED_OUTPUT: 1
     network_mode: "host"
     command: bash -c "ros2 launch fleet_adapter_invisibot fleet_adapter.launch.xml config_file:=/fleet_adapter_invisibot_ws/src/fleet_adapter_invisibot/config.yaml nav_graph_file:=/fleet_adapter_invisibot_ws/src/fleet_adapter_invisibot/nav_graph.yaml server_uri:=${WS_URL:-ws://localhost:8000}/_internal use_sim_time:=false enable_workcell:=true"
     depends_on:
      rmf_core:
        condition: service_healthy
     restart: unless-stopped
   invisibot:
     container_name: invisibot_c
     image: ghcr.io/cardboardcode/invisibot:latest
     network_mode: "host"
     command: bash -c "python3 -m invisibot"
   door_adapter_mock:
     container_name: door_adapter_mock_c
     image: ghcr.io/cardboardcode/door_adapter_mock:jazzy
     volumes:
      - ./door_config.yaml:/door_adapter_mock_ws/src/door_adapter_mock/configs/config.yaml
     environment:
       RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
       RCUTILS_COLORIZED_OUTPUT: 1
     network_mode: "host"
     command: bash -c "source /ros_entrypoint.sh && ros2 launch door_adapter_mock run.launch.xml config_file:=/door_adapter_mock_ws/src/door_adapter_mock/configs/config.yaml"
     restart: unless-stopped
   lift_adapter_mock:
     container_name: lift_adapter_mock_c
     image: ghcr.io/cardboardcode/lift_adapter_mock:jazzy
     environment:
       RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
       RCUTILS_COLORIZED_OUTPUT: 1
     network_mode: "host"
     command: bash -c "source /ros_entrypoint.sh && ros2 launch lift_adapter_mock run.launch.py config_file:=/lift_adapter_mock_ws/src/lift_adapter_mock/configs/config.yaml"
     restart: unless-stopped