services:
   rmf_core:
     volumes:
      - ./delivery_queue/:/rmf_core_ws/map/delivery_queue
      - ./delivery_queue/debug.rviz:/rmf_core_ws/install/rmf_core/rviz/debug.rviz
     command: > 
        bash -c "python3 /rmf_core_ws/src/rmf_core/rviz/update_map_name.py /rmf_core_ws/map/delivery_queue/delivery_queue.building.yaml &&
        ros2 launch rmf_core start_rmf_core.launch.xml
        config_file:=/rmf_core_ws/map/delivery_queue/delivery_queue.building.yaml
        viz_config_file:=/rmf_core_ws/install/rmf_core/rviz/debug.rviz
        headless:=${HEADLESS:-true}"
   fleet_adapter_invisibot:
     volumes:
      - ./fleet_config.base.yaml:/fleet_adapter_invisibot_ws/src/fleet_adapter_invisibot/config.yaml
      - ./delivery_queue/nav_graph.yaml:/fleet_adapter_invisibot_ws/src/fleet_adapter_invisibot/nav_graph.yaml
   invisibot:
     volumes:
       - ./robots.base.json:/invisibot_ws/robots.json
   lift_adapter_mock:
     scale: 0
   door_adapter_mock:
     scale: 0